language: c
env:
  - HB_VER=3.0.0 HB_DIR=harbour-3.0.0 HB_URL=https://downloads.sourceforge.net/harbour-project/source/3.0.0/harbour-3.0.0-src.zip
  - HB_VER=3.2-dev HB_DIR=core-master HB_URL=https://github.com/harbour/core/archive/master.zip
  - HB_VER=3.4-dev HB_DIR=harbour-core-master HB_URL=https://github.com/vszakats/harbour-core/archive/master.zip
compiler: gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq libncurses-dev
  - sudo apt-get install -qq libslang2-dev
  - sudo apt-get install -qq libpcre3-dev
  - sudo apt-get install -qq zlib1g-dev
  - sudo apt-get install -qq unzip
install:
  - wget $HB_URL -O /tmp/harbour-$HB_VER.zip
  - cd /tmp && unzip harbour-$HB_VER.zip && cd -
  - cd /tmp/$HB_DIR && HB_INSTALL_PREFIX=/usr/local HB_BUILD_3RDEXT=no HB_BUILD_CONTRIBS=xhb make && cd -
  - cd /tmp/$HB_DIR && sudo make install && cd -
  - sudo ldconfig -f /usr/local/etc/ld.so.conf.d/harbour.conf
  - wget https://github.com/endersonmaia/hbunit/releases/download/0.0.5-alpha/hbunit-0.0.5-alpha-linux.tgz
  - tar -xvzf hbunit-0.0.5-alpha-linux.tgz libhbunit.a
script:
  - make
  - make test
