#ifndef _STOMP_SOCKET_CH
#define _STOMP_SOCKET_CH

#define STOMP_SOCKET_BUFFER_SIZE 4098

// CONNECTION ERRORS

#define STOMP_SOCKET_OPEN_ERROR               2
#define STOMP_SOCKET_CONNECT_ERROR            3
#define STOMP_SOCKET_STATUS_SEND_FAILED       4

#endif