#ifndef _STOMP_FRAME_HEADER_CH
#define _STOMP_FRAME_HEADER_CH

// GENERAL
#define STOMP_ACCEPTED_VERSIONS_HEADER_NAME			"accepted-versions"
#define STOMP_ACCEPTED_VERSIONS_HEADER_VALUE       	"1.0,1.1,1.2"

#endif